### ISSUE TITLE
Single pane with multiple windows doesn't work

### ISSUE THREAD

**Issue by alexcaza** [alexcaza/weztermocil#3]
Running this template doesn't produce expected results. Second and third tabs don't launch commands in the single pane:

```yaml
windows:
  - name: dev
    root: ~/Documents/programming/unsplash-web
    layout: tiled
    panes:
      # This should be kept in sync with [ref:run_app_dev_command].
      - just
      - just lint
      - just typecheck
  - name: editor 
    root: ~/Documents/programming/unsplash-web
    layout: tiled
    panes:
      - hx .
  - name: git
    root: ~/Documents/programming/unsplash-web
    layout: tiled
    panes:
      - lazygit
```
